# Generated by Django 3.2.13 on 2022-06-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agpk', '0003_auto_20220520_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Метоположение'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='AGPK', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='owner',
            field=models.CharField(max_length=20, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(verbose_name='Вьезд'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Жилец'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agpk.rooms', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agpk.hotels', verbose_name='Общежитие'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'premium'), ('2', 'deluxe'), ('3', 'basic')], max_length=50, verbose_name='Тип комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomnumber',
            field=models.IntegerField(verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='size',
            field=models.IntegerField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('1', 'available'), ('2', 'not available')], max_length=15, verbose_name='Статус'),
        ),
    ]
