# Generated by Django 3.2.13 on 2022-06-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agpk', '0006_auto_20220614_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
    ]
