# Generated by Django 3.2.13 on 2022-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agpk', '0009_remove_reservation_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость'),
        ),
    ]
